### PR TITLE
[Issue-2]: enable fpu emulation and nodejs package

### PR DESCRIPTION
**Pull request by jempatel**

### CODE REVIEW

**Comment by jempatel** [comment]
Successfully created Firmware with FPU emulation. All node packages are also compiled successfully. 

The only difference compared to the last testing here was node packages are compiled as modules and installed using `opkg` after flashing the firmware.

After installing the node, when a simple js program was executed, It was crashed with an error

```
root@OpenWrt:~# node server.js 


#
# Fatal error in, line 0
# unreachable code
#
#
#
#FailureMessage Object: 0x7fe4675c
Trace/breakpoint trap
```

Tracing and debugging the root cause for the same now.

**Comment by greenbreakfast** [comment]
@jempatel I tried this out on my end and had success.

I compiled the firmware and node packages on a server. I installed the Omega2+ firmware on a device, and manually copied over and installed the node package and its dependencies.

I then ran two node test programs, and both worked as expected (details below).

What does the server.js program you're trying to run look like? 
Please try running the 2 simple test programs below to see if they work on your end.

---

`test1.js`:
```
console.log("Hello World!")
```
Got `Hello World!` output on stdout

---


`test2.js`:
```
var http = require("http");

http.createServer(function (request, response) {
   // Send the HTTP header 
   // HTTP Status: 200 : OK
   // Content Type: text/plain
   response.writeHead(200, {'Content-Type': 'text/plain'});
   
   // Send the response body as "Hello World"
   response.end('Hello World\n');
}).listen(8081);

// Console will print the message
console.log('Server running at http://127.0.0.1:8081/');
```
Got the "server running" message on stdout and saw `Hello World` text in browser when I navigated to the Omega's local IP address at port 8081

**Comment by jempatel** [comment]
Chances are my local environment is a problem, I have to stop builds in between most of the time. because with the default config from OpenWrt, it's taking more than 10 hours to compile full firmware in my local environment as It creates SDK and image builder. My local build environment is probably getting messed up in this build process.

**Comment by greenbreakfast** [comment]
Merging this in and deleting the development branch.
Node is building and running basic programs on the device. We'll look into it more if we find issues.

**Pull request merged**
