### PR TITLE
init: initial commit for onion build wrapper

### PR DESCRIPTION
**Pull request by jempatel**

### CODE REVIEW

**Comment by greenbreakfast** [comment]
Looking pretty good so far. I have a few comments:

## Target Device Selection

I made `build.sh` exit right after we do the defconfig on line 173. When I go into the `openwrt` directory and run `make menuconfig`, I see that all of the mt76x8 target devices are selected:
image

Perhaps in our config diff file, we need to specify `N` for all of the devices we don't want to build?

## Extra Config Files and Naming

It's a small item, but I'd like to rename `omegaX.config` to `onion.config` 
And let's remove the `omega2.config` and `omega2p.config files`, they don't really add any thing and could cause confusion for users

## Instructions in Readme

Could you please add a few basic instructions to the readme on how to use this wrapper?

**Comment by jempatel** [comment]
> Looking pretty good so far. I have a few comments:
> ## Target Device Selection
> 
> I made `build.sh` exit right after we do the defconfig on line 173. When I go into the `openwrt` directory and run `make menuconfig`, I see that all of the mt76x8 target devices are selected: image
> 
> Perhaps in our config diff file, we need to specify `N` for all of the devices we don't want to build?
> ## Extra Config Files and Naming
> 
> It's a small item, but I'd like to rename `omegaX.config` to `onion.config` And let's remove the `omega2.config` and `omega2p.config files`, they don't really add any thing and could cause confusion for users
> ## Instructions in Readme
> 
> Could you please add a few basic instructions to the readme on how to use this wrapper?

All comments are addressed.

**Comment by greenbreakfast** [comment]
@jempatel looks good, I'm good to merge this in. 

Just had 2 questions: 

## Firmware Image Prefix

Can you point me to where the `openwrt-v22.03.3-ramips-mt76x8-` prefix is set for the firmware images in `openwrt/bin/targets/ramips/mt76x8`:

image

## Kernel Checksum

Since we're compiling the same kernel modules and packages as the official 22.03.3 release, I would expect our build to have the same version info and [kernel checksum](https://forum.openwrt.org/t/kernel-version-mismatch-after-building-kernel-and-packages/136437).

The version info matches:
image

But our kernel checksum does not.
Ours:
image

OpenWRT 22.03.3 release:
image

Can you please take a quick look into why this is the case?

**Comment by jempatel** [comment]
> @jempatel looks good, I'm good to merge this in.
> 
> Just had 2 questions:
> ## Firmware Image Prefix
> 
> Can you point me to where the `openwrt-v22.03.3-ramips-mt76x8-` prefix is set for the firmware images in `openwrt/bin/targets/ramips/mt76x8`:

Its set from `include/image.mk` line no [40](https://github.com/openwrt/openwrt/blob/0a32f66fea95cabc5d21c945678d918bed8cca47/include/image.mk#L40).

It sets a variable `IMG_PREFIX`.

> 
> image
> ## Kernel Checksum
> 
> Since we're compiling the same kernel modules and packages as the official 22.03.3 release, I would expect our build to have the same version info and [kernel checksum](https://forum.openwrt.org/t/kernel-version-mismatch-after-building-kernel-and-packages/136437).
> 
> The version info matches: image
> 
> But our kernel checksum does not. Ours: image
> 
> OpenWRT 22.03.3 release: image
> 
> Can you please take a quick look into why this is the case?

This does not look like I can have a look quickly as it needs multiple changes and kernel build to see the effect, I already tried replicating kernel version strings which might be affecting checksum majorly to be the same as the upstream build.

```
SOURCE_DATE_EPOCH
CONFIG_KERNEL_BUILD_USER="builder"
CONFIG_KERNEL_BUILD_DOMAIN="buildhost"
```

**Comment by greenbreakfast** [comment]
@jempatel thanks for the response, nothing further required for the vanilla build, I've merged this PR in.

### Firmware image 
Is this `IMG_PREFIX` set by the `VERSION` that's set in our profile config?

### Kernel Checksum
Ok, not a major issue at the moment. No need to spend any more time on it.

**Comment by jempatel** [comment]
> @jempatel thanks for the response, nothing further required for the vanilla build, I've merged this PR in.
> ### Firmware image
> 
> Is this `IMG_PREFIX` set by the `VERSION` that's set in our profile config?
> ### Kernel Checksum
> 
> Ok, not a major issue at the moment. No need to spend any more time on it.

That one was from the openwrt default system, It reads the .config file and based on the config settings, it sets the image prefix.

**Comment by jempatel** [comment]
@greenbreakfast I tried a clean build by keeping the .config file the same as upstream, and it creates a kernel image with the same checksum.
The only difference we have in our config is we have only selected onion profiles and deselected all others.

**Comment by jempatel** [comment]
kernel version magic would change after enabling FPU.

**Comment by greenbreakfast** [comment]
Ok, understood. Thanks for confirming. No need to do anything further with the kernel checksum.

**Pull request merged**
