### PR TITLE
optimize build process

### PR DESCRIPTION
**Pull request by jempatel**

### CODE REVIEW

**Comment by greenbreakfast** [comment]
@jempatel see my code review comment above

**Comment by jempatel** [comment]
> @jempatel see my code review comment above

I did find any comment

**Comment by greenbreakfast** [comment]
@jempatel ah strange, I had made a code review comment about a specific line in the commit. Here is what it says about the `do_run` function:

Does this mean the compile command will still run with `V=99` but the output will be silent?
I'd like to avoid this since 1) the verbose outputs adds to the overall compilation time even if we're silencing it, and 2) the compilation output without the `V=99` flag is still useful.

Can we add the verbose flag instead of piping to null? 
By that I mean: `$* V=99` when `VERBOSE` is set to 1, and just `$*` when `VERBOSE` is set to 0?

**Comment by jempatel** [comment]
> @jempatel ah strange, I had made a code review comment about a specific line in the commit. Here is what it says about the `do_run` function:
> 
> Does this mean the compile command will still run with `V=99` but the output will be silent? I'd like to avoid this since 1) the verbose outputs adds to the overall compilation time even if we're silencing it, and 2) the compilation output without the `V=99` flag is still useful.
> 
> Can we add the verbose flag instead of piping to null? By that I mean: `$* V=99` when `VERBOSE` is set to 1, and just `$*` when `VERBOSE` is set to 0?

yes, handled openwrt `make` with the `VERBOSE` spacial case.

**Pull request merged**
